services:

  shorten-url-svc:
    container_name: shorten-url-svc-ct
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_DATABASE_URL=${MONGO_DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      mongo-svc:
        condition: service_started
      redis-svc:
        condition: service_started
    networks:
      - shorten-url-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 2

  mongo-svc:
    container_name: mongo-svc-ct
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - shorten-url-network

  redis-svc:
    image: redis:7
    container_name: redis-svc-ct
    ports:
      - "6379:6379"
    networks:
      - shorten-url-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - shorten-url-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - shorten-url-svc

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - shorten-url-network
    depends_on:
      - prometheus

networks:
  shorten-url-network:
    driver: bridge

