global:
  scrape_interval: 5s  # How often to scrape metrics

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['shorten-url-svc:8080']  # Docker service name
        labels:
          application: 'url-shortener'